import 'dotenv/config';
import pg from 'pg';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createApp} from './app.js';
const dir=path.dirname(fileURLToPath(import.meta.url));
const required=['DATABASE_URL','APP_URL','XOLVIS_BASE_URL','XOLVIS_CONNECTOR_API_KEY','XOLVIS_API_USER','XOLVIS_API_PASSWORD','XOLVIS_PUBLIC_INTEGRATION_KEY','XOLVIS_CALLBACK_URL'];
for(const key of required) if(!process.env[key]) throw new Error(`Missing environment variable: ${key}`);
if(!process.env.XOLVIS_ERROR_URL && !process.env.XOLVIS_CANCEL_URL) throw new Error('Set XOLVIS_ERROR_URL or XOLVIS_CANCEL_URL');
if(!process.env.XOLVIS_SUCCESS_URL && !process.env.XOLVIS_SUCCESS_URL_3795) console.warn('Set a default success URL for pages that do not supply one.');
const appUrl=new URL(process.env.APP_URL);
if(appUrl.protocol !== 'https:' && process.env.NODE_ENV === 'production') throw new Error('APP_URL must use https');
const dbUrl=new URL(process.env.DATABASE_URL);
const ca=process.env.DATABASE_CA_CERT?.replace(/\\n/g,'\n');
if(ca) for(const key of ['sslmode','sslcert','sslkey','sslrootcert']) dbUrl.searchParams.delete(key);
const pool=new pg.Pool({connectionString:dbUrl.toString(),...(ca?{ssl:{ca,rejectUnauthorized:true}}:{}),max:10,connectionTimeoutMillis:10000});
pool.on('error',error=>console.error('Database connection error:',error.code));
await pool.query(await fs.readFile(path.join(dir,'schema.sql'),'utf8'));
const server=createApp({pool,publicDir:path.join(dir,'public')}).listen(Number(process.env.PORT||8080),'0.0.0.0',()=>console.log('Checkout server ready'));
for(const signal of ['SIGTERM','SIGINT']) process.on(signal,()=>server.close(async()=>{await pool.end();process.exit(0);}));
